# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('galleryID', models.AutoField(primary_key=True, serialize=False)),
                ('gallery', models.CharField(max_length=255)),
                ('galleryDescription', models.CharField(max_length=255)),
                ('create_dt', models.DateField()),
                ('edit_dt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('galleryImageID', models.AutoField(primary_key=True, serialize=False)),
                ('isCover', models.BooleanField(default=False)),
                ('galleryID_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageManager.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('imageDescription', models.CharField(max_length=255)),
                ('create_dt', models.DateField()),
                ('edit_dt', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='imageID_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageManager.Image'),
        ),
    ]
